# -*- coding: utf-8 -*-
"""ai_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aX_EtOwzF1d6hBds4JiIQsVghNCh6fYU
"""

import pandas as pd
import numpy as np
data=pd.read_csv('how_ai_agents_think_and_act.csv')
data.head(5)

data.drop(['step_id'],axis=1,inplace=True)
data.head(5)

data.tail(5)

data['tool_input'] = data['tool_input'].notna()
data.head(5)

data['tool_name'] = data['tool_name'].notna()
data.head(5)

data.info()

data.to_csv('processed_data.csv', index=False)
print('DataFrame successfully saved to processed_data.csv')